### ISSUE TITLE
Latest Firefox Messing With Plugins?

### ISSUE THREAD

**Issue by Caynadian** [downthemall/anticontainer#109]
I'm running Firefox 45 and I can't seem to get Anti-container to load any plugins.  The list just comes up empty.  Clicking on create plugin or install plugin doesn't do anything either.  I have tried downloading DownThemAll/Anti-Container in to a fresh empty profile and the same thing happens.  Are you having the same issue?

**Comment by githubsucks2** [comment]
Yes, it is broken, the authors have not responded.

**Comment by marianocarrazana** [comment]
i will check this,tomorrow (maybe) the bug will be solved

**Comment by Caynadian** [comment]
Many thanks!

---
Chris Krohn
chris.krohn@gmail.com

**Comment by poke** [comment]
I have a likely fix ready for the problems on anticontainer’s end. But at this point, we have to first wait for DownThemAll! to get fixed which is experiencing similar issues. So right now, I can’t test my fix because dtA! still breaks. I’ll let you know as soon as I hear something.

**Comment by nmaier** [comment]
@poke the 2.0 and 3.0 DTA branches up to today's Firefox Nightly (I hope)
Also pushed some anticontainer fixes. Is this fixed now?

**Comment by poke** [comment]
@nmaier Unfortunately no.

On 2.x, I cannot find any links. If I right-click and download links explicitly, the download is added, and everything seems to work. With e10s enabled, I also get a lot of “unsafe CPOW usage” warnings in `integration/elements.js`.

With AC enabled, I get an error in `manager.js`: `s.getUsableFileName is not a function`. I’ll see if I can fix that myself later.

On 3.x, the download selection works, and the download itself also seems to work fine. There are a few errors in the browser console though:

```
DownThemAll! (error) - [object XULElement]
	load/findLinks/</<() @ chrome://dta-modules/content/loaders/integration.js:290
	load/findLinks/<() @ chrome://dta-modules/content/loaders/integration.js:280
```

```
DownThemAll! (error) - reloadFilters(): [Exception: this._box is null]
    Filters.reloadFilters@chrome://dta/content/preferences/prefs.js:188:4
    Filters.Observer.observe@chrome://dta/content/preferences/prefs.js:168:5
…
TypeError: $(...) is null
DownThemAll! (error) - data:text/css,treechildren::-moz-tree-image(iconic,FileIconunknown)%20{list-style-image:%20url(moz-icon://file.unknown?size=16)%20!important;-moz-image-region:%20auto%20!important;width:%2016px%20!important;}@media%20(min-resolution:%202dppx)%20{treechildren::-moz-tree-image(iconic,FileIconunknown)%20{list-style-image:%20url(moz-icon://file.unknown?size=32)%20!important;}}
    FileExtensionSheet.prototype<.getAtom() @ chrome://dta-modules/content/support/fileextsheet.js:45
```

If I enable AC, I earlier had Firefox become completely unresponsive when I opened anything DTA related. Not sure what that was. After switiching it on and off a few times (to test the other cases), it seems to work now. The mentioned AC error also does not appear there, and the download including AC unboxing works.

**Comment by nmaier** [comment]
>With e10s enabled, I also get a lot of “unsafe CPOW usage” warnings in integration/elements.js.

@poke, that's to be expected in dta-2, and fixed soon in dta-3 once I cleanup my outgoing queue and push..

**Comment by poke** [comment]
@nmaier What do you think, can we push fixed versions of DTA 2 and AC to AMO yet?

**Comment by nmaier** [comment]
I'm planning to to this over the weekend, @poke.

**Comment by Caynadian** [comment]
@nmaier I was just wondering if you had a chance to finish the update?

**Comment by nmaier** [comment]
@Caynadian Sorry, got sidetracked, will do this weekend aka tomorrow.

**Comment by nmaier** [comment]
A still unreviewed-by-mozilla version is available here now: https://addons.mozilla.org/firefox/addon/downthemall-anticontainer/versions/ It should best be used with the also still unreviewed-by-mozilla https://addons.mozilla.org/firefox/addon/downthemall/versions/ or a DownThemAll! nightly

**Comment by Caynadian** [comment]
Awesome!  It's working again.  Thanks!

**Comment by mbiLJ** [comment]
It isn't working for me. I bypassed the add-on signing controls so that I
could install both of the unreviewed add-ons. In DTA manager I can see the
plugins listed in the Anti-Container tab, but I've tried downloading images
from a Facebook album page, a Picasa Web Gallery, and a coppermine gallery
and all I am getting are the thumbnails and a lot of html pages.

I'm curious -- on the Links page in DTA there is a checkbox for
Anti-Container, but on the Pictures and Media page there is not. Why is
that?

**Comment by poke** [comment]
> but I've tried downloading images from a Facebook album page

I’m really sorry about that. I have been meaning to update those plugins this weekend so they would be fixed in the new version but in the end I didn’t make it in time. I’ve already done most of the work, so I’ll verify that everything is working and push the changes later today. I’ll also take a look at Picasa and Coppermine and see what’s going on there.

I’ll also reintroduce what we did a few years ago, publishing “nightly” unsigned packages, so those that want to try the latest stuff don’t have to wait for the extension update to go through the full AMO process.

I’ll use the issue #114 to track the progress on those broken plugins. If you know other ones, please leave a comment there, and I’ll take a look.
